---
title: "Data Care and Feeding"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- 
use this code for comments between chunks
-->

```{r, Installing Libraries}

library(tidyverse)
library(skimr)        ## install.packages("skimr")
#  this is part of tidyverse -- library(dplyr)

library(gapminder)  #install.packages("gapminder")

#
#in console
#   str(gapminder)
#   print(gapminder, n=10)
#   
#   to make a df into tibble use x1 <- as_tibble(original_df)  
#   
#   dim(df) will show dimensions of the df
#   

#simple plot use base R


```

### Simple Plots of Data
```{r, simple plots of data}

str(gapminder)
print(gapminder, n=10)

plot(lifeExp ~ year, gapminder)
plot(lifeExp ~ gdpPercap, gapminder)
plot(lifeExp ~ log(gdpPercap), gapminder)

hist(gapminder$lifeExp)
```


### Looking at Variables
```{r, looking at variables}

hist(gapminder$lifeExp)  #lifeExp is a numeric variable
summary(gapminder$lifeExp)
summary(gapminder$year) #year is an integer
table(gapminder$year)

#factor Data
summary(gapminder$continent) #continent is a factor

table(gapminder$continent)
#barplot(table(gapminder$continent))
```

### Demonstration of ggplot
```{r, Demo of ggplot}

p <- ggplot(filter(gapminder, continent != "Oceania"),
            aes(x = gdpPercap, y = lifeExp)) # just initializes, creates a base of the data to graph, excludes "Oceania"

p <- p + scale_x_log10() # log the x axis the right way, further defines "p"

p + geom_point() # scatterplot

p + geom_point(aes(color = continent)) # map continent to color as an aesthetic for a new scatterplot, note that Oceania is not in the legend

p + geom_point(alpha = (1/3), size = 3) + geom_smooth(lwd = 1.5, se = FALSE)
#> `geom_smooth()` using method = 'gam' and formula 'y ~ s(x, bs = "cs")'
# size = diameter of the point (try 13)
# alpha = color density of the point, but not sure what it is based on (try 1/13 or 3)
# lwd = line width
# se = a cloud to illustrate the standard error
# 
#  this would be good code to use with the maple sap data


p + geom_point(alpha = (1/3), size = 3) + facet_wrap(~ continent) +
  geom_smooth(lwd = 1.5, se = FALSE)
#> `geom_smooth()` using method = 'loess' and formula 'y ~ x'

```


###Filtering Data
```{r, Filter Data}

filter(gapminder, lifeExp <29)  #retain rows/observations with lifeExp less than 29. if <31, the number of observations increases

filter(gapminder, country == "Rwanda", year > 1979) 
# selects rows that are both Rwanda and year greater than 1979
#factor variables are selected within "value", and numeric/integer are not in quotes

filter(gapminder, country == "Rwanda" | year > 1979, lifeExp > 80)
# selects rows for country = Rwanda or year > 1979...and lifeExp > 80
# if the symbol | is changed to a comma then the decision is x or y or z
# if the symbol | is changed to &, the decision is more restrictive



```


### Selecting Data Columns
```{r, Selecting Data}

gapminder %>%  # extract two variables and show the first four rows
  select(year, lifeExp) 
  #select(-continent, -pop)  #this code would retain all variable except continent and pop
  head(4)

str(gapminder) # the output of the above selection does not change the structure of the tibble

gapminder %>% 
  select(yr = year, lifeExp, gdpPercap) %>%  #renames year as yr
  select(gdpPercap, everything()) #move gdpPercap to first position, then all other


```


### Single Table dplyr Functions
```{r, Mutate and Within Tibble Percentages}

my_gap <- gapminder %>%  #mutate defines and inserts new variable into a tibble
  mutate(gdp = pop * gdpPercap)

canada <- my_gap %>% 
  filter(country == "Canada") #%>% 
  filter(!c(country == "Algeria" & year ==1987))
#the last line makes for an unequal number of levels for Algeria vs. Canada
#this tests if the next code accounts for that inequality.
#if the number of levels are not equal, the following code fails.

pct_tibble <- my_gap %>% 
  #this would be better with a join command
  mutate(tmp = rep(canada$gdpPercap, nlevels(country)),
         gdpPercapRel = gdpPercap / tmp)  # use following to drop "tmp"
   #       ,
   #      tmp = NULL)

#  in the above code, "rep" is to replicate the gdpPercap of Canada for each of
#  the number of levels of country. I assume that 

visualize <- pct_tibble %>% 
  filter(country == "Algeria"| country == "Canada") %>% 
  filter(year > 1982) %>% 
  select( -lifeExp, -continent)
print(visualize, n=15)


summary(pct_tibble$gdpPercapRel)



```


### Arrange (= Sort by)
```{r, Arranging Data in Sequence}

my_gap %>% 
  arrange(year, country) #sorts by country within each year

my_gap %>% 
  filter(year == 2007) %>% 
  arrange(lifeExp) # retains year = 2007, sorts by life expectancy
        # low to high

my_gap %>% 
  filter(year == 2007) %>%  # no " " for numeric
  arrange(desc(lifeExp)) # same as previous, but high to low


```

###Changing Names of Variables
```{r, Changing names of variables with "rename"}

my_gap %>% #new name = old name
  rename(
    life_exp = lifeExp,
    gdp_percap = gdpPercap
  )
```


###Group and Summarize
```{r, Group and Summarize}
test <- my_gap %>% # this send the output to df=test with two variables
  group_by(continent) %>% 
  summarize(
    n = n()
  )

test2 <- my_gap %>% # the resultant df is same as above=test
  count(continent)


my_gap %>% 
  group_by(continent) %>% 
  summarize(
    n = n(),
    n_countries = n_distinct(country) #counts number of countries within a continent
  )

#calculate the mean life expectancy by continent
my_gap %>% 
  group_by(continent) %>% 
  summarize(
    avg_life_exp = mean(lifeExp)
  )

#"summarize_at" applies same statistic to multiple variables
#compute life exp and GDPpercap by continent and year for 1952 & 2007
my_gap %>% 
  filter(year %in% c(1952, 2007)) %>% #filters for year within 1952 and 2007
  group_by(continent, year) %>% 
  summarize_at(
    vars(lifeExp, gdpPercap), 
    list(~mean(.), ~median(.)))

my_gap %>% 
  filter(continent == "Asia") %>% 
  group_by(year) %>% 
  summarize(
    min_lifeExp = min(lifeExp),
    max_lifeExp = max(lifeExp)
  )


```

###Group-Wise Summaries
```{r, Group-Wise Summaries}
#the "first" function of mutate uses the first value of a variable
#within the defined group. Seems like there might be "last" or "sum"
#There are more options (nth, first, or last). see help for nth dplyr

ascending <- my_gap %>% 
  group_by(country) %>% 
  select(country, year, lifeExp) %>% 
  mutate(
    lifeExp_gain = lifeExp - first(lifeExp)
  ) %>% 
  filter(year < 1963)
head(ascending, n=15)

descending <- my_gap %>% 
  arrange(country, desc(lifeExp)) %>% 
  group_by(country) %>% 
  select(country, year, lifeExp) %>% 
  mutate(
    lifeExp_gain = lifeExp - first(lifeExp) #by "desc" the first value was the largest within the country. Could have use df=ascending and last rather than first
  ) %>% 
  filter(year < 1963)
head(descending, n=15)

```






